#!/bin/bash

echo "🚀 Deploying Paralegal AI Assistant to Vercel..."
echo ""
echo "✅ Vercel CLI is already installed!"
echo ""
echo "📝 Please run these commands:"
echo ""
echo "cd /home/z/my-project"
echo "vercel login"
echo "vercel deploy --prod"
echo ""
echo "🎯 This will:"
echo "- Deploy your app to Vercel"
echo "- Give you a URL like: https://your-app.vercel.app"
echo "- Takes about 5 minutes"
echo "- Your mom can use it from any device!"
echo ""
echo "Need help? Check README.md for detailed instructions!"
